ignore quantic in merge group

diff --git a/.github/workflows/prbot.yml b/.github/workflows/prbot.yml
--- a/.github/workflows/prbot.yml
+++ b/.github/workflows/prbot.yml
@@ -245,15 +245,47 @@ jobs:
     secrets:
       SFDX_AUTH_CLIENT_ID: ${{ secrets.SFDX_AUTH_CLIENT_ID }}
       SFDX_AUTH_JWT_KEY: ${{ secrets.SFDX_AUTH_JWT_KEY }}
-  is-valid:
+  is-valid-pr:
     name: 'Confirm build is valid'
-    if: ${{ always() }}
+    if: ${{ always() && github.event_name == 'pull_request'}}
     needs:
       - 'build'
       - 'lint-check'
       - 'unit-test'
       - 'e2e-atomic-test'
       - 'e2e-quantic'
+      - 'e2e-atomic-screenshots'
+      - 'e2e-atomic-react-test'
+      - 'e2e-atomic-react-nextjs-test'
+      - 'e2e-iife-test'
+      - 'e2e-atomic-angular-test'
+      - 'e2e-atomic-vuejs-test'
+      - 'e2e-atomic-stencil-test'
+      - 'e2e-atomic-hosted-page-test'
+      - 'e2e-atomic-insight-panel-test'
+      - 'e2e-headless-ssr-test-app-dev'
+      - 'e2e-headless-ssr-test-app-prod'
+      - 'e2e-headless-ssr-test-pages-dev'
+      - 'e2e-headless-ssr-test-pages-prod'
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          success="${{ !contains(needs.*.result, 'cancelled') && !contains(needs.*.result, 'failure')}}"
+          if [[ $success == "true" ]]; then
+            echo "Build is valid"
+            exit 0
+          else
+            echo "Build is invalid"
+            exit 1
+          fi
+  is-valid-merge-queue:
+    name: 'Confirm build is valid'
+    if: ${{ always() && github.event_name == 'merge_group'}}
+    needs:
+      - 'build'
+      - 'lint-check'
+      - 'unit-test'
+      - 'e2e-atomic-test'
       - 'e2e-atomic-screenshots'
       - 'e2e-atomic-react-test'
       - 'e2e-atomic-react-nextjs-test'
