chore: ensure unicity of job name
otherwise, statuscheck might get confused

diff --git a/.github/workflows/prbot.yml b/.github/workflows/prbot.yml
--- a/.github/workflows/prbot.yml
+++ b/.github/workflows/prbot.yml
@@ -328,7 +328,7 @@ jobs:
       SFDX_AUTH_CLIENT_ID: ${{ secrets.SFDX_AUTH_CLIENT_ID }}
       SFDX_AUTH_JWT_KEY: ${{ secrets.SFDX_AUTH_JWT_KEY }}
   is-valid-pr:
-    name: 'Confirm build is valid'
+    name: 'Confirm build is valid (PR)'
     if: ${{ always() && github.event_name == 'pull_request'}}
     needs:
       - 'build'
@@ -363,7 +363,7 @@ jobs:
             exit 1
           fi
   is-valid-merge-queue:
-    name: 'Confirm build is valid'
+    name: 'Confirm build is valid (merge group)'
     if: ${{ always() && github.event_name == 'merge_group'}}
     needs:
       - 'build'
@@ -388,6 +388,22 @@ jobs:
     steps:
       - run: |
           success="${{ !contains(needs.*.result, 'cancelled') && !contains(needs.*.result, 'failure')}}"
+          if [[ $success == "true" ]]; then
+            echo "Build is valid"
+            exit 0
+          else
+            echo "Build is invalid"
+            exit 1
+          fi
+  is-valid:
+    name: 'Confirm build is valid'
+    needs:
+      - 'is-valid-pr'
+      - 'is-valid-merge-queue'
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          success="${{ contains(needs.*.result, 'success')}}"
           if [[ $success == "true" ]]; then
             echo "Build is valid"
             exit 0
